// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	model "github.com/1ambda/go-ref/service-gateway/pkg/api/model"
)

// FindAllOKCode is the HTTP code returned for type FindAllOK
const FindAllOKCode int = 200

/*FindAllOK list of access logs

swagger:response findAllOK
*/
type FindAllOK struct {

	/*
	  In: Body
	*/
	Payload model.FindAllOKBody `json:"body,omitempty"`
}

// NewFindAllOK creates FindAllOK with default headers values
func NewFindAllOK() *FindAllOK {

	return &FindAllOK{}
}

// WithPayload adds the payload to the find all o k response
func (o *FindAllOK) WithPayload(payload model.FindAllOKBody) *FindAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find all o k response
func (o *FindAllOK) SetPayload(payload model.FindAllOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(model.FindAllOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FindAllDefault generic error response

swagger:response findAllDefault
*/
type FindAllDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *model.Error `json:"body,omitempty"`
}

// NewFindAllDefault creates FindAllDefault with default headers values
func NewFindAllDefault(code int) *FindAllDefault {
	if code <= 0 {
		code = 500
	}

	return &FindAllDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find all default response
func (o *FindAllDefault) WithStatusCode(code int) *FindAllDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find all default response
func (o *FindAllDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find all default response
func (o *FindAllDefault) WithPayload(payload *model.Error) *FindAllDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find all default response
func (o *FindAllDefault) SetPayload(payload *model.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindAllDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
