version: '3.5'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=goref
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
       - ./scripts/docker-mysql/:/etc/mysql/conf.d

  etcd:
    image: quay.io/coreos/etcd:latest
    environment:
      ETCD_NAME: etcd
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LOG_PACKAGE_LEVELS: "*=INFO"
      # ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      # ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      # ETCD_INITIAL_CLUSTER: infra3=http://etcd3:2380,infra1=http://etcd1:2380,infra2=http://etcd2:2380
      # ETCD_INITIAL_CLUSTER_STATE: new
      # ETCD_INITIAL_CLUSTER_TOKEN: etcd-01
    ports:
     - "2379:2379" # client
     - "2380:2380" # cluster

  etcd-ui:
    image: soyking/e3w:latest
    volumes:
      - ./scripts/docker-etcd-ui/config.local.ini:/app/conf/config.default.ini
    ports:
      - "2381:8080"
    depends_on:
      - etcd

#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:3-management
#    restart: always
#    volumes:
#      - ./scripts/docker-rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
#    ports: # https://www.rabbitmq.com/networking.html
#      - 5672:5672 # client
#      - 15672:15672 # admin
#      - 61613:61613 # stomp
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "rabbit-cookie"
#      RABBITMQ_DEFAULT_USER: "guest"
#      RABBITMQ_DEFAULT_PASS: "guest"
#      RABBITMQ_DEFAULT_VHOST: "/"
#  redis:
#    container_name: redis
#    image: redis:4
#    restart: always
#    ports:
#      - 6379:6379

