version: '3.3'

services:
  redis:
    container_name: redis
    image: redis:4
    restart: always
    ports:
      - 6379:6379
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=goref
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ./scripts/docker-rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports: # https://www.rabbitmq.com/networking.html
      - 5672:5672 # client
      - 15672:15672 # admin
      - 61613:61613 # stomp
    environment:
      RABBITMQ_ERLANG_COOKIE: "rabbit-cookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
