// Code generated by go-swagger; DO NOT EDIT.

/*
Package rest Gateway API
API Spec for Gateway


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package rest
