// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API Spec for Gateway",
    "title": "Gateway API",
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/access": {
      "get": {
        "tags": [
          "access"
        ],
        "operationId": "findAll",
        "responses": {
          "200": {
            "description": "list of access logs",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/access"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "access"
        ],
        "operationId": "addOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/access"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/access"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "tags": [
          "access"
        ],
        "operationId": "findOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/access"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/access"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "access"
        ],
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/access"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/access"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "access"
        ],
        "operationId": "removeOne",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "access": {
      "type": "object",
      "required": [
        "browserName",
        "browserVersion",
        "osName",
        "osVersion",
        "isMobile",
        "language",
        "timezone",
        "timestamp",
        "userAgent"
      ],
      "properties": {
        "browserName": {
          "type": "string"
        },
        "browserVersion": {
          "type": "string"
        },
        "isMobile": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "osName": {
          "type": "string"
        },
        "osVersion": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "timezone": {
          "type": "string"
        },
        "userAgent": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "timestamp",
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "timestamp": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API Spec for Gateway",
    "title": "Gateway API",
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/access": {
      "get": {
        "tags": [
          "access"
        ],
        "operationId": "findAll",
        "responses": {
          "200": {
            "description": "list of access logs",
            "schema": {
              "$ref": "#/definitions/findAllOKBody"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "access"
        ],
        "operationId": "addOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/access"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/access"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{id}": {
      "get": {
        "tags": [
          "access"
        ],
        "operationId": "findOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/access"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/access"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "access"
        ],
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/access"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/access"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "access"
        ],
        "operationId": "removeOne",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "access": {
      "type": "object",
      "required": [
        "browserName",
        "browserVersion",
        "osName",
        "osVersion",
        "isMobile",
        "language",
        "timezone",
        "timestamp",
        "userAgent"
      ],
      "properties": {
        "browserName": {
          "type": "string"
        },
        "browserVersion": {
          "type": "string"
        },
        "isMobile": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "osName": {
          "type": "string"
        },
        "osVersion": {
          "type": "string"
        },
        "timestamp": {
          "type": "string"
        },
        "timezone": {
          "type": "string"
        },
        "userAgent": {
          "type": "string"
        },
        "uuid": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "timestamp",
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "timestamp": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "findAllOKBody": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/access"
      },
      "x-go-gen-location": "operations"
    }
  }
}`))
}
