// Code generated by MockGen. DO NOT EDIT.
// Source: internal/websocket/websocket_manager.go

// Package websocket is a generated GoMock package.
package websocket

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockWebSocketManager is a mock of WebSocketManager interface
type MockWebSocketManager struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketManagerMockRecorder
}

// MockWebSocketManagerMockRecorder is the mock recorder for MockWebSocketManager
type MockWebSocketManagerMockRecorder struct {
	mock *MockWebSocketManager
}

// NewMockWebSocketManager creates a new mock instance
func NewMockWebSocketManager(ctrl *gomock.Controller) *MockWebSocketManager {
	mock := &MockWebSocketManager{ctrl: ctrl}
	mock.recorder = &MockWebSocketManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWebSocketManager) EXPECT() *MockWebSocketManagerMockRecorder {
	return m.recorder
}

// Broadcast mocks base method
func (m *MockWebSocketManager) Broadcast(message *WebSocketMessage) {
	m.ctrl.Call(m, "Broadcast", message)
}

// Broadcast indicates an expected call of Broadcast
func (mr *MockWebSocketManagerMockRecorder) Broadcast(message interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockWebSocketManager)(nil).Broadcast), message)
}

// SubscribeConnectionCount mocks base method
func (m *MockWebSocketManager) SubscribeConnectionCount() <-chan string {
	ret := m.ctrl.Call(m, "SubscribeConnectionCount")
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// SubscribeConnectionCount indicates an expected call of SubscribeConnectionCount
func (mr *MockWebSocketManagerMockRecorder) SubscribeConnectionCount() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeConnectionCount", reflect.TypeOf((*MockWebSocketManager)(nil).SubscribeConnectionCount))
}

// Stop mocks base method
func (m *MockWebSocketManager) Stop() <-chan bool {
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(<-chan bool)
	return ret0
}

// Stop indicates an expected call of Stop
func (mr *MockWebSocketManagerMockRecorder) Stop() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWebSocketManager)(nil).Stop))
}
