// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Access access
// swagger:model access
type Access struct {

	// browser name
	// Required: true
	BrowserName *string `json:"browserName"`

	// browser version
	// Required: true
	BrowserVersion *string `json:"browserVersion"`

	// id
	ID int64 `json:"id,omitempty"`

	// is mobile
	// Required: true
	IsMobile *string `json:"isMobile"`

	// language
	// Required: true
	Language *string `json:"language"`

	// os name
	// Required: true
	OsName *string `json:"osName"`

	// os version
	// Required: true
	OsVersion *string `json:"osVersion"`

	// timestamp
	// Required: true
	Timestamp *string `json:"timestamp"`

	// timezone
	// Required: true
	Timezone *string `json:"timezone"`

	// user agent
	// Required: true
	UserAgent *string `json:"userAgent"`

	// uuid
	UUID string `json:"uuid,omitempty"`
}

// Validate validates this access
func (m *Access) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBrowserName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateBrowserVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateIsMobile(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateLanguage(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOsName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOsVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTimestamp(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTimezone(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUserAgent(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Access) validateBrowserName(formats strfmt.Registry) error {

	if err := validate.Required("browserName", "body", m.BrowserName); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateBrowserVersion(formats strfmt.Registry) error {

	if err := validate.Required("browserVersion", "body", m.BrowserVersion); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateIsMobile(formats strfmt.Registry) error {

	if err := validate.Required("isMobile", "body", m.IsMobile); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateLanguage(formats strfmt.Registry) error {

	if err := validate.Required("language", "body", m.Language); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateOsName(formats strfmt.Registry) error {

	if err := validate.Required("osName", "body", m.OsName); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateOsVersion(formats strfmt.Registry) error {

	if err := validate.Required("osVersion", "body", m.OsVersion); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateTimestamp(formats strfmt.Registry) error {

	if err := validate.Required("timestamp", "body", m.Timestamp); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateTimezone(formats strfmt.Registry) error {

	if err := validate.Required("timezone", "body", m.Timezone); err != nil {
		return err
	}

	return nil
}

func (m *Access) validateUserAgent(formats strfmt.Registry) error {

	if err := validate.Required("userAgent", "body", m.UserAgent); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Access) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Access) UnmarshalBinary(b []byte) error {
	var res Access
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
