swagger: "2.0"
info:
  description: API Spec for Gateway
  title: Gateway API
  version: 0.0.1
schemes:
- http
consumes:
- application/json
produces:
- application/json
basePath: /api
paths:
  /access:
    get:
      tags:
        - access
      operationId: findAll
#      parameters:
#        - name: since
#          in: query
#          type: integer
#          format: int64
#        - name: limit
#          in: query
#          type: integer
#          format: int32
#          default: 20
      responses:
        200:
          description: list of access logs
          schema:
            type: array
            items:
              $ref: "#/definitions/access"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - access
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/access"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/access"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      tags:
        - access
      operationId: findOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/access"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/access"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - access
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/access"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/access"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - access
      operationId: removeOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  access:
    type: object
    required:
      - browserName
      - browserVersion
      - osName
      - osVersion
      - isMobile
      - language
      - timezone
      - timestamp
      - userAgent
    properties:
      browserName:
        type: string
      browserVersion:
        type: string
      osName:
        type: string
      osVersion:
        type: string
      isMobile:
        type: string
      language:
        type: string
      timestamp:
        type: string
      timezone:
        type: string
      userAgent:
        type: string
      # non-required fields
      uuid:
        type: string
  error:
    type: object
    required:
      - timestamp
      - code
      - message
    properties:
      timestamp:
        type: integer
        format: int64
      code:
        type: string
      message:
        type: string
