swagger: "2.0"
info:
  description: REST API Spec for Gateway
  title: GatewayRestApi
  version: 0.0.1
schemes:
- http
consumes:
- application/json
produces:
- application/json
basePath: /api
paths:
  /access:
    get:
      tags:
        - access
      operationId: findAll
      parameters:
        - name: itemCountPerPage
          in: query
          type: integer
          format: int64
          default: 10
        - name: currentPageOffset
          in: query
          type: integer
          format: int32
          default: 0
      responses:
        200:
          description: access records with pagination info
          schema:
            type: object
            properties:
              rows:
                type: array
                items:
                  $ref: "#/definitions/access"
              pagination:
                $ref: "#/definitions/pagination"

        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - access
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/access"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/access"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /access/{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    get:
      tags:
        - access
      operationId: findOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/access"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/access"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - access
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/access"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/access"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - access
      operationId: removeOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  pagination:
    type: object
    required:
      - itemCountPerPage  # limit
      - currentPageOffset # offset
      - totalItemCount    # count
    properties:
      itemCountPerPage:
        type: integer
        format: int64
      currentPageOffset:
        type: integer
        format: int32
      totalItemCount:
        type: integer
        format: int64
  access:
    type: object
    required:
      - browserName
      - browserVersion
      - osName
      - osVersion
      - isMobile
      - language
      - timezone
      - timestamp
      - userAgent
    properties:
      browserName:
        type: string
      browserVersion:
        type: string
      osName:
        type: string
      osVersion:
        type: string
      isMobile:
        type: string
      language:
        type: string
      timestamp:
        type: string
      timezone:
        type: string
      userAgent:
        type: string
      # non-required fields
      id:
        type: integer
        format: int64
      uuid:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      timestamp:
        type: string
      code:
        type: integer
        format: int64
      message:
        type: string
